  language: python
  python:
    - "3.6"

  install:
    - pip3 install flask flask_httpauth passlib flask-mongoengine

  services:
    - mongodb

  script:
    - python3 -m unittest -v tests.test_app
